Data Management
---------------
(((Data Management)))

Introduction
~~~~~~~~~~~~

Libraries generate a lot of data.  Evergreen can only report on data that is being collected and stored in the database.  It's important
to ensure that data you need is being entered consistently and that your staff know
what data to collect and where in Evergreen to enter it.  If data is missing or incorrect it can cause problems for your patrons
using the library, your staff helping your patrons, and any statistics your library collects and may need to report on.

Co-op Support recommends reviewing what data your library currently collects and considering whether 
you're collecting unnessary data or not collecting needed data; both can be true.  To protect your patrons you should only be 
collecting the information necessary to provide your services to them.

The best practices outlined in this chapter are intended to assist libraries in collecting and managing their library's data in 
Sitka's Evergreen in a consistent manner.  This includes recommendations on local policies to create, features and functions in
Evergreen that can be used, and report templates that can be run to catch incorrect or missing data.

Getting Started
~~~~~~~~~~~~~~~

When embarking on a data management project there is some set up and potential staff training involved.

Co-op Support recommends starting with the following:

. Determine what data should be collected.  
.. This is includes data that must be collected, that could be collected, and data that shouldn't be collected.
. Document what data should be collected and values should be used for things like patron profiles, circulation modifiers, etc.
. Where possible in Evergreen, set up templates and customizations to show what values should be used and data collected.
. Set up recurring reports in Evergreen to report out on things that should be checked on a regular basis. 
. Ensure applicable staff know how to use the interfaces in Evergreen designed to track potential issues such as Hopeless Holds and 
the Transit List.
. Ensure your staff know your policies and procedures for handling your data.

It's very easy to pick the wrong circulation modifier or patron profile or statistical category value by accident; having policies, 
procedures, templates, and recurring reports in place with staff aware of them should help significantly to cut down on future 
incorrect or missing data.  


Checklist
~~~~~~~~~

The intervals given here are general recommendations.  Libraries may find that certain tasks should be run
more or less frequently at their library.

Annual Tasks
^^^^^^^^^^^^

* Enter known https://docs.libraries.coop/sitka/_closed_dates_editor.html[Closed dates] for the year
* Review your library https://docs.libraries.coop/sitka/_organizational_units.html#_library_main_settings[contact details],
 https://docs.libraries.coop/sitka/_organizational_units.html#_library_addresses[addresses], and 
 https://docs.libraries.coop/sitka/_organizational_units.html#operation-hour[hours of operation] 
* Review your https://docs.libraries.coop/sitka/_library_settings_editor.html[library settings]
* Review your https://docs.libraries.coop/sitka/_circulation_policies.html[circulation policies]
* Review https://docs.libraries.coop/sitka/_hold_policies.html[hold policies]
* Review your https://docs.libraries.coop/sitka/_group_penalty_thresholds.html[group penalty thresholds]
* Review your https://docs.libraries.coop/sitka/_shelving_location_editor.html[shelving locations]
* Review your https://docs.libraries.coop/sitka/_statistical_categories_patron_editor.html[patron statistical categories] 
and associated values
* Review your https://docs.libraries.coop/sitka/_statistical_categories_item_editor.html[item statistical categories] 
and associated values
* Review cataloguing templates (https://docs.libraries.coop/sitka/_holdings_templates.html[holdings],
 https://docs.libraries.coop/sitka/_using_library_specific_marc_templates.html[MARC]) to ensure they are up to date and 
 staff are using the same templates
* Review your https://docs.libraries.coop/sitka/_notifications_action_triggers.html[patron notifications]
* Review https://docs.libraries.coop/sitka/_print_templates.html[receipt templates] on relevant workstations
* Review the logo and colours used for your https://docs.libraries.coop/sitka/_public_catalogue_customizations.html[public catalogue]
* Review the reports run by your library and the templates used ADD LINK
* Review any xref:_integrated_3rd_party_services[3rd party services] and ensure discontinued services are reported to Co-op Support if they
authenticated against Evergreen.

Quarterly Tasks
^^^^^^^^^^^^^^^

* https://docs.libraries.coop/sitka/_searching_for_library_staff_accounts.html[Search for library staff accounts] and confirm they 
are up to date and are only for current staff
* Delete pre-catalogued items that have a status of Cataloguing
* Resolve any https://docs.libraries.coop/sitka/_hopeless_holds.html[Hopeless Holds]
* Check the https://docs.libraries.coop/sitka/_transit_list.html[Transit List] for items that have been in transit longer than normal
* Check for https://docs.libraries.coop/sitka/_patrons_with_negative_balances.html[patrons with negative balances] and resolve as appropriate

Monthly Tasks
^^^^^^^^^^^^^

* Run and review reports for the following and resolve issues revealed: 
** https://docs.libraries.coop/sitka/_collection_management.html#_title_amp_item_count_by_shelving_location_and_circulation_modifier[Current
Collection]
** https://docs.libraries.coop/sitka/items_collection_management.html#_circ_modifier_copies_without_circ_modifier[Items
 Without Circulation Modifiers]
**  https://docs.libraries.coop/sitka/_collection_management.html#_status_all_items_with_selected_item_status[Items in an Unavailable
Item Status - damaged, lost, missing, etc.]
** https://docs.libraries.coop/sitka/_patron_management.html#_total_patron_count_by_patron_profiles[Patron Profiles]

[NOTE]
======
Reports can be set up as recurring reports or run as needed.

If you want to set up recurring reports but monthly is too frequent for your library, consider setting the recurrence interval to
*4 Month(s)* (quarterly) or *6 Month(s)* (biannually).
======


Ongoing Tasks
^^^^^^^^^^^^^
* Clear your https://docs.libraries.coop/sitka/_holds_shelf.html#_clearing_holds[holds shelf]
* Correct incorrect fixed fields as you come across them to ensure bibliographic records have https://docs.libraries.coop/sitka/_search_filters_and_format_icons.html[correct 
icons and appear as expected in search results]
* Check your https://docs.libraries.coop/sitka/_pull_list_for_hold_requests.html[holds pull list]
* https://docs.libraries.coop/sitka/_closing_library_staff_accounts.html[Close staff accounts] when staff leave the library

Cleaning Up Your Existing Data
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

As you work through this checklist you may find a significant amount of data clean up is needed for your existing data. This can be 
a daunting task and Co-op Support recommends deciding what is of priority to the library and then working through it as staff have 
capacity.

For example, you may decide that resolving hopeless holds is a high priority for your library so that patrons aren't waiting months for
holds that are never going to come.

Recommendations
~~~~~~~~~~~~~~~

Local Library Policies and Procedures
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Libraries should maintain local lists of:

* https://docs.libraries.coop/sitka/_circulation_modifiers.html[circulation modifiers] used by the library and what type of item specific modifiers should be used for.
* information to be collected in the patron account
* information that specifically should not be collected in the patron account
* patron main (profile) permissions groups used by the library and which how to decide which one to use for a patron
* any other information where library staff need to know what specific values to select or what information is important to collect

Templates
^^^^^^^^^

Evergreen has a number of templates that can be set up to save staff time and help keep data consistent:

* https://docs.libraries.coop/sitka/_holdings_templates.html[Holdings Templates]
* https://docs.libraries.coop/sitka/_using_library_specific_marc_templates.html[Library Specific MARC Templates]
* https://docs.libraries.coop/sitka/_import_templates.html[MARC Batch Import Templates]
* https://docs.libraries.coop/acquisitions/_setting_up_load_marc_order_records.html[Load MARC Order Records Templates - Acquisitions Module]
* https://docs.libraries.coop/sitka/_serials_administration.html#serial-item-template[Serial Item Templates]
* https://docs.libraries.coop/sitka/_prediction_pattern_templates.html[Prediction Pattern Templates]
* https://docs.libraries.coop/sitka/_print_templates.html[Receipt Templates]

Working with Your Collection
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Regularily running a report on your https://docs.libraries.coop/sitka/_collection_management.html#_title_amp_item_count_by_shelving_location_and_circulation_modifier[current
collection] enables you to see at a glance where data issues may lie. With this report you're able to see at a glance if you have items without circulation modifiers and if you have items with circulation
modifier/shelving location combinations that don't make sense for your library. You can then run additional reports to discover
what items need to be reviewed and possibly updated. Report templates found in the _Item List by Item Attributes_ folder are especially
helpful.  This folder is found under _Shared Folders -> Templates -> Sitka_templates -> Collection_.

* https://docs.libraries.coop/sitka/_collection_management.html#_circ_modifier_copies_with_selected_circ_modifiers[Circ Modifier: 
Copies with Selected Circ Modifiers]
* https://docs.libraries.coop/sitka/items_collection_management.html#_circ_modifier_copies_without_circ_modifier[Items
 Without Circulation Modifiers]
* Shelving Location: Items with Selected Shelving Location
* Shelving Location and Circ Modifier: Items with Selected Shelving Location and Circ Modifier

You can use the output from these reports to easily batch edit items through Item Status.  Instructions on loading report files 
through Item Status can be found in the section called Upload from File ADD LINK in Sitka's Evergreen Documentation.

Co-op Support strongly recommends setting up and using https://docs.libraries.coop/sitka/_holdings_templates.html[holdings 
templates] when cataloguing items. If you have multiple cataloguers we recommend setting up templates on one cataloguers account
and then https://docs.libraries.coop/sitka/_holdings_templates.html#_sharing_holdings_template[sharing them] with any other cataloguers.
Holdings templates are commonly used to automatically apply values for shelving locations, circulation modifier, age hold protection, 
loan duration, and statistical categories. 

Co-op Support also recommends library staff set their https://docs.libraries.coop/sitka/_holdings_editor_preferences.html[Holdings 
Editor Preferences]. This allows staff to hide item attributes not used by their library.  Staff are less likely to enter values
in a field not used if it's not visible in the Holdings Editor.


Working with Your Patrons
^^^^^^^^^^^^^^^^^^^^^^^^^

The following best practices will help with consistent data collection for patron accounts:

* Customize the drop down for the https://docs.libraries.coop/sitka/_permission_tree_display_entries.html[Main (Profile) Permission 
Group] field in the patron account.
* https://docs.libraries.coop/sitka/_patron_account_fields.html#_customizing_the_display_fields[Customize the display fields] 
for the patron account.
* Set applicable https://docs.libraries.coop/sitka/_statistical_categories_patron_editor.html[patron statistical categories]
 as required to ensure values are filled in.
* Ensure _Free Text_ is set to false for https://docs.libraries.coop/sitka/_statistical_categories_patron_editor.html[patron statistical 
categories] where consistent values are needed. 

Public Catalogue
^^^^^^^^^^^^^^^^

At least once a year library staff should check the logo and colours used on their public catalogue
to make sure they are current and match what is used on your website. If your library has additional
links beside your logo they should be checked as well to ensure they are still current. 

In Sitka's Evergreen Documentation, the https://docs.libraries.coop/sitka/_public_catalogue_customizations.html[section called
Public Catalogue Customizations] outlines what can be customizes in your public catalogue.

Please contact https://bc.libraries.coop/support/[Co-op Support] if your public catalogue needs to be updated.

Reporting
^^^^^^^^^

In Sitka's Evergreen Documentation, the https://docs.libraries.coop/sitka/_maintaining_reporter_data.html[section called Maintaining 
Reporter Data] outlines best practices for handling reporter data.

Local system administrators should:

* periodically run a report using the template https://docs.libraries.coop/sitka/_local_administration_3.html#_reports_run_in_specified_time_period_by_specified_library[Reports Run In Specified Time Period By Specified Library] 
to see what reports are being run at their library. 
* ensure reports aren't being run directly off of Sitka templates.
* ensure reports aren't being run from accounts for former staff members.
* check to see if there are newer templates avaiable after every Evergreen upgrade.

Safeguarding Your Data
~~~~~~~~~~~~~~~~~~~~~~

Library staff accounts and authentication accounts for 3rd party services permit access to Evergreen and all the 
data for your library contained within.

Library Staff Accounts
^^^^^^^^^^^^^^^^^^^^^^

Co-op Support strongly recommends: 

* encouraging all staff to update their passwords on a regular basis and ensure passwords are kept private.
* checking that staff have the appropriate level of permissions for the tasks they need to perform and updating their 
main (profile) permission group if they have a higher level of access than needed.
* tracking who has https://docs.libraries.coop/sitka/_local_administration_3.html#_staff_assigned_to_supplementary_permission_group_s[additional access] to reports and the acquisitions module.
* https://docs.libraries.coop/sitka/_searching_for_library_staff_accounts.html[reviewing your staff accounts]
 to ensure only staff currently working at the library have access to the library system.

[NOTE]
======
If you see staff accounts with the name Sitka please leave them be.  These are troubleshooting 
accounts used by Co-op Support.
========

Integrated 3rd Party Services
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you cancel a subscription or retire a piece of hardware, like a self check, that authenticates
through Evergreen please let Co-op Support know as soon as possible.  This enables us to remove 
accounts associated with the service so that your patrons' information is no longer available 
to the vendor.
