Data Management
---------------
(((Data Management)))

Introduction
~~~~~~~~~~~~

Libraries generate a lot of data.

Co-op Support recommends reviewing what data your library currently collects and considering whether 
you're collecting unnessary data or not collecting needed data; both can be true.

Evergreen can only report on data that is being collected and stored in the database.  It's important
to ensure that data you need is being entered consistently and that your staff know
what data to collect and where in Evergreen to enter it.  For example, if your library provides 
services to multiple constituencies you may need to report on how many patrons are in each.

To protect your patrons you should only be collecting the information necessary to provide your
services to them.   



Checklist
~~~~~~~~~

The intervals given here are general recommendations.  Libraries may find that certain tasks should be run
more or less frequently at their library.

Annual
^^^^^^

* Closed dates
* library information
** in Evergreen
** with the Co-op
* circulation policies
* hold policies
* patron notifications
* shelving locations
* report templates
* group penalty thresholds
* library settings
* templates - holdings, MARC, etc.
* review any discontinued 3rd party services
* public catalogue


Quarterly
^^^^^^^^^

* items without circulation modifiers
* run and review current collection report
* patron stat cats
* run and review patron group report
* library staff accounts
* delete pre-cats



Monthly
^^^^^^^

* Hopeless Holds
* Transit List
* holds shelf
* patrons with negative balances
* run and review reports on Unavailable Item Statuses


Ongoing
^^^^^^^

* Fixed fields
* pull list

Your Library
~~~~~~~~~~~~

Library information

Collection
~~~~~~~~~~

* current collection report

* use templates - holdings, MARC, MARC batch import/export for both cat and acq

Circulation Modifiers
^^^^^^^^^^^^^^^^^^^^^
* maintain a list of the circulation modifiers your library uses


Circulation Modifier Name - type of items the modifier are used for

Fixed Fields
^^^^^^^^^^^^

Item Statuses
^^^^^^^^^^^^^

* run reports on lost, missing, mending, cleaning, etc.

Weeding
^^^^^^^

Inventory
^^^^^^^^^

Pre-catalogued items
^^^^^^^^^^^^^^^^^^^^

Shelving Locations
^^^^^^^^^^^^^^^^^^


Circulation
~~~~~~~~~~~

* circ and hold policies
* closed dates
* group penalty thresholds
* patron notifications
* hopeless holds
* pull list for hold requests
* holds shelf
* transit list
* patron permission groups - have Co-op Support customize what shows
* remove identification (if applicable)
* patrons with negative balances
* patron stat cats

Reporting
~~~~~~~~~

* Report on reports
* don't run from Sitka templates
* check to see if there are newer templates



Library Staff Accounts
~~~~~~~~~~~~~~~~~~~~~~

* encourage staff to update passwords on a regular basis - link to policy
* check permission levels
* who has additional access - reports, acq, carousels
* check staff still work at the library

[NOTE]
======
If you see staff accounts with the Sitka please leave them be.  These are troubleshooting 
accounts used by Co-op Support.
========

Public Catalogue
~~~~~~~~~~~~~~~~

At least once a year library staff should check the logo and colours used on their public catalogue
to make sure they are current and match what is used on your website. If your library has additional
links beside your logo they should be checked as well to ensure they are still current. 

Please contact 
Co-op Support your public catalogue needs to be updated.

Integrated 3rd Party Services
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you cancel a subscription or retire a piece of hardware, like a self check, that authenticates
through Evergreen please let Co-op Support know as soon as possible.  This enables us to remove 
accounts associated with the service so that your patrons' information is no longer available 
to the vendor.

