Temporary Library Closures
--------------------------
(((Emergency Closures)))

If your library is closed temporarily there are a number of things you and Co-op Support can do 
to alert patrons and reduce staff workload.  While some of these steps can be completed by 
library staff, Co-op Support will handle it if your closure is due to an emergency and you
have limited or no access to Evergreen.

If your library uses LibPress for your website, please refer the 
https://help.libraries.coop/libpress/10-temporary-closures/[Temporary Library Closures] section in
the LibPress documentation for step by step instructions on updating your website for the closure.

Please contact https://bc.libraries.coop/support/[Co-op Support] by phone, email, or 
through the contact form for assistance or if you have any other questions.

.Library Closure Quick Checklist
* Add Closure in Evergreen
* Add notice to your website
* Add a banner to your public catalogue
* Turn off Interlibrary Connect
* Turn off local holds
* Update patrons about to expire


Add a Closing In Evergreen
~~~~~~~~~~~~~~~~~~~~~~~~~~

The first thing libraries should do is add a closing in Evergreen using the 
http://docs.libraries.coop/sitka/_closed_dates_editor.html[Closed Dates Editor]. 

For planned closures this should be done well in advance to ensure that due dates won't 
fall within your closure.

For unplanned closures libraries need to use the 
http://docs.libraries.coop/sitka/_closed_dates_editor.html#_emergency_closing[Emergency
Closing] functionality in Evergreen.  This is important because it will will move the due dates 
for anything due in the period you specify as well as notify your patrons that 
the library is closed and due dates have been changed.

If you expect to be closed for several days or longer use the closing type _Multiple Days_ and
pick an end date that falls after you expect to re-open.  Evergreen will move all due dates that fall
in-between the chosen dates to be due back the day after the end date.  You can add additional emergency closures as needed
 to continue to extend your due dates.
 
When you have a re-opening date we recommend ensuring your final closure end date is at least a 
few days ahead of your actual re-opening so that all of your items aren't due on the day of your
re-opening.  
 
While this can be done by any local system administrator for your library, Co-op Support will add
the closure if you have limited or no access to Evergreen. Please contact 
https://bc.libraries.coop/support/[Co-op Support]
and include the start and end dates you would like used.


Interlibrary Connect and Local Holds
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If libraries are not able to access their collections during a closure to fill ILC or 
local holds we recommend
asking Co-op Support to turn both off.  This reduces the backlog for filling ILC and local 
holds that your library will have when you re-open.

Depending on the situation you may decide to turn off ILC but leave local holds turned on.  For
example, if your library is able to do curbside pick-up you may want patrons to be able to place holds
on items in your collection but due to staff limitations not want to be shipping/receiving items
for ILC. 

If applicable to your situation, libraries participating in ILC or BC One Card should also contact their
provincial body for assistance in getting the word out to other libraries to please not send 
items to the library until further notice.

Updating Expiring Patrons
~~~~~~~~~~~~~~~~~~~~~~~~~

Depending on the length of your closure you may want to ensure patron accounts won't expire
so that patrons are still able to access your digital resources.

Co-op Support can batch update the expiry for patrons falling within a specified period.
For example, all patrons expiring within the next 3 months can have their expiration date
updated. 


Messaging to Patrons
~~~~~~~~~~~~~~~~~~~~

Co-op Support recommends posting a message on your website to alert patrons to the current situation.
If you use LibPress for your website Co-op Support can update it for you if you don't have 
easy access to do so yourself.

.Sample text for your website that you can modify to suit your emergency situation.
----
The YOUR LIBRARY is temporarily closed due to X.  Holds and interlibrary loan requests cannot be 
placed at this time.  Due dates for your items have been extended and fines will not be charged.
Please do not return items to the library.  While we're closed our digital library remains available
LINK TO APPLICABLE RESOURCES.  Thank you for keeping the library items at home until further notice.
----

Co-op Support also recommends a banner on your public catalogue.  For libraries using Evergreen's
public catalogue Co-op Support can add the banner for you.  Libraries using a discovery layer may need
to contact their vendor for assistance.


.Sample text for your banner that you can modify to suit your emergency situation. 
----
The YOUR LIBRARY is temporarily closed.  For more information see our website (this is a link 
to your website). While we're closed our digital library remains available
LINK TO APPLICABLE RESOURCES.  Please keep the library items at home until further notice.
----

If the closure is going to be a long closure Co-op Support can also turn off email notifications 
for courtesy and overdue notices to ensure your patrons don't receive them while the library is closed.

When you have a re-opening date for your library Co-op Support can set up a temporary additional 
courtesy notice to go out more than 3 days before the item is due and include information about when the library
is re-opening and how patrons should handle returns. For example, we can set up a courtesy notice
to go out 7 days ahead of the due date with information that the library will be re-opening on
X date for these hours and that patrons can start returning items to the drop box or in the library
on or after that date.

Re-Opening Your Library
~~~~~~~~~~~~~~~~~~~~~~~

The steps to re-open your library will depend on which features/functions you turned off.

. Ensure the _End Date_ for your final Emergency Closure is the day before you re-open.
. Ask Co-op Support to update your public catalogue banner with information on your re-opening or
remove the banner altogether.
. Update your website with information on your re-opening.
. Ask Co-op Support to turn local holds and ILC holds back on.  These can be turned on separately if
you wish to delay restarting ILC.
. If applicable, let other libraries know to start sending your items home.
. Ask Co-op Support to turn email notifications back on.
. Ask Co-op Support to add a temporary additional courtesy notice which includes re-opening details.

Please contact https://bc.libraries.coop/support/[Co-op Support] if you have any questions 
about re-opening your library.


