Cataloguing Standards
~~~~~~~~~~~~~~~~~~~~~
(((Cataloguing Policy)))
(((MARC 21 Format for Bibliographic Data)))
(((Normes MARC 21)))
(((RDA)))
(((Subject Headings)))
(((Classification)))
(((Training)))




All staff performing cataloguing functions in Sitka's Evergreen are expected to follow 
the same cataloguing standards when working with records. 

Bibliographic Records
^^^^^^^^^^^^^^^^^^^^^

Cataloguers are expected to follow cataloguing standards when creating new bibliographic records 
or editing existing bibliographic records in Sitka's Evergreen.

New bibliographic records should follow current https://www.rdatoolkit.org/[RDA] and 
https://www.loc.gov/marc/[MARC 21 Format for Bibliographic Data]/
https://www.marc21.ca/M21/BIB/B001-Sommaire.html[Normes MARC 21] standards.

[NOTE]
======
Older records in the catalogue may follow AACR2 standards, rather than RDA, 
depending on when they were originally catalogued.

To minimize duplication of records, when an existing AACR2 record is already in the 
Sitka database for the title being catalogued cataloguers should attach their holdings 
to it rather than importing a new RDA record.
======

Policies for Sitka's requirements for a minimum record and what constitutes a good record
are found xref:_the_bibliographic_record[].

Non-Bibliographic Records
^^^^^^^^^^^^^^^^^^^^^^^^^

Cataloguers may create records for non-bibliographic items.  
It is recommended that cataloguers generally follow cataloguing standards when creating these 
records (i.e. enter a name for the item in the 245 title field) but these records do 
not need to meet the same standards as bibliographic records.

Libraries should create their own non-bibliographic records rather than attaching to existing ones from
other libraries unless they are working with a shared collection.

Instructions for creating non-bibliographic records can be found in Sitka's Evergreen 
Documentation in the section called 
https://docs.libraries.coop/sitka/_creating_new_records_for_non_bibliographic_resources.html[Creating
New Records for Non-Bibliographic Resources].

Subject Headings
^^^^^^^^^^^^^^^^

When assigning subject headings libraries should use terms from an official thesaurus such as 
Library of Congress Subject Headings, LC Subject headings for children's literature, 
Medical Subject Headings, Canadian Subject Headings, and Répertoire de vedettes-matière.

Subject headings not included in official thesauri are considered local subject headings and must be entered 
as such in Sitka's Evergreen.

Local Subject Headings
++++++++++++++++++++++
[[_local_subject_headings]]

Local subject headings are used when the official subject headings are not sufficient 
to describe the title being catalogued.  This is often the case with materials that are
specific to an area or use a local term.
 
Cataloguers may create and include local subject headings in bibliographic records.
Local subject headings MUST be entered into a 
xref:_library_specific_local_information[69X MARC field and include a $5 with the 
library's code].


Sitka Subject Headings
++++++++++++++++++++++
[[_sitka_subject_headings]]

The Sitka team is working with member libraries to identify and remove harmful subject headings 
from the Sitka catalogue.  Many of these subject headings are still in the official thesauri.
A list of removed subject headings and their replacements will be available when the 
first changes are made to the live database.

Where subject headings have been replaced through the work of the Co-op and the 
Cataloguing Working Group the MARC field will have a $2SITKALIST to indicate that the 
subject heading is coming from the official Sitka list of subject headings.  These subject 
headings are considered official headings, rather than local, and will be found in 
the 6XX fields rather than the 69X fields.

When working with records where the Sitka subject headings apply, cataloguers should:

* NOT remove the Sitka subject headings and associated coding
* NOT add the harmful subject heading
* add the new subject headings to relevant bibliographic records

Classification Systems
^^^^^^^^^^^^^^^^^^^^^^

While bibliographic records are shared within Sitka's Evergreen, call number and item records are not.  
Libraries are free to use whatever classification system(s) meets their needs for their call numbers. 

Libraries should enter local call numbers through the holdings editor, and not into the bibliographic record. 

Instructions for using the holdings editor can be found in Sitka's Evergreen Documentation 
in the section called 
http://docs.libraries.coop/sitka/_maintaining_holdings.html#_holdings_editor[Holdings Editor].

Cataloguing Training
^^^^^^^^^^^^^^^^^^^^

The BC Libraries Cooperative provides resources and continuing training on how to catalogue in relation 
to Sitka's Evergreen.  We do not provide training in cataloguing standards.

If library staff need basic or advanced cataloguing training on RDA, MARC coding, 
subject analysis, and/or classification we encourage you to look at the programs offered 
by the library schools, training offered through library associations, and online cataloguing
resources.