Editing Bibliographic Records
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Existing Records
^^^^^^^^^^^^^^^^

level of skill

Cataloguers should always 

Cataloguers may wish to add additional information to the record to improve it.  Cataloguers
must ensure that the information they add does not change the title being described.

Leader and Fixed Fields
^^^^^^^^^^^^^^^^^^^^^^^

The fixed fields, also called control fields, in the MARC record contain coded information
that is used by Evergreen's 
http://docs.libraries.coop/sitka/_search_filters_and_format_icons.html[search filters and 
format icons]. It is important that these fields are coded correctly or your patrons 
will not be able to find the titles they are looking for when using search filters.

The values for the characters in these fields are found in 
https://www.loc.gov/marc/bibliographic/[MARC21 Format for Bibliographic Data]:

* https://www.loc.gov/marc/bibliographic/bdleader.html[Leader]
* https://www.loc.gov/marc/bibliographic/bd006.html[006]
* https://www.loc.gov/marc/bibliographic/bd007.html[007]
* https://www.loc.gov/marc/bibliographic/bd008.html[008]

[NOTE]
======
All bibliographic records will have a leader and 008 field.  Whether a 006 and/or 007 is
required will depend on the type of material the record is for. 
======

Incorrect or missing values in these fields are an ongoing issue as older records
and some vendor records are not coded correctly.  Co-op Support encourages libraries
correct the coding in these fields.

Instructions on editing the leader and 008 field can be found in the section called
http://docs.libraries.coop/sitka/_editing_marc_record_leader_and_fixed_field_008.html[Editing
MARC Record Leader and Fixed Field 008].

Instructions on editing the 007 field can be found in the section called 
http://docs.libraries.coop/sitka/_fixed_field_007_physical_characteristics_wizard.html[Fixed
Field 007 Physical Characteristics Wizard].


Overlaying Records
^^^^^^^^^^^^^^^^^^

Cataloguers with sufficient cataloguing knowledge can overlay brief and on order records
with full records via Z30.50 or by batch loading full records.  Before
overlaying records cataloguers must ensure the 
xref:_is_it_a_match[records are a match].

Instructions on overlaying records via Z39.50 can be found in the section called
http://docs.libraries.coop/sitka/_adding_bibliographic_records.html#_overlaying_records_via_z39_50_interface[Overlaying
Records via Z39.50].

Working with On Order Records
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Working with On-order MARC Records
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Use of the Acquisitions Module resulted in an increase in the number of brief on-order records in the Sitka catalogue. The Acquisitions Ad Hoc Committee put forth recommendations on handling these brief on-order records. These recommendations were originally approved by the Business Function Group March 21, 2012, and have since been updated by Co-op Support in 2014 and 2018.

* Acquisitions Selectors to follow guidelines for minimum cataloguing requirements in creating brief on-order records.

* Cataloguers can only use brief on-order records to add holdings to if no other, better, record exists in the Sitka catalogue. An Acquisitions library , or another qualified cataloguer at a Sitka library, will change the on-order record to a full bibliographic record in the end, so cataloguers need to make sure they're attaching their holdings to the correct brief bibliographic record.

* If the only record for a title in the catalogue is an on-order record, cataloguers should use that record to add holdings to only if they are sure that it matches format and isbn or other identifier to the title-in-hand. In this situation, cataloguers can overlay or merge the on-order record with the complete record as long as the format and identifier are a definite match and the new record adheres to Sitka Cataloguing Policy. Cataloguers must also ensure that they carry over any 590 or 690 fields from the on-order record to the complete record. (updated Feb 2014)

* If the only record for a title in the catalogue is an on-order record, and it is unclear which format or isbn or other identifier the on-order record describes, cataloguers should bring in a new record via Z39.50 and attach their holdings to it. (updated Feb 2014)

* Cataloguers can overlay brief on-order records when using the MARC Batch Import/Export function. When importing, cataloguers must always use the Sitka overlay profile to ensure data in the 590 and 690 fields of the original record is preserved. Cataloguers should ensure that the brief records is for the same format as the item they are cataloguing. By default, brief on-order records use the Book 008 field regardless of the true format of the item.




Merging Records
^^^^^^^^^^^^^^^

Cataloguers with sufficient cataloguing knowledge can merge duplicate records together.  Before
merging records cataloguers must ensure the 
xref:_is_it_a_match[records are a match].

For instructions on merging bibliographic records together please refer to the section 
called http://docs.libraries.coop/sitka/_merging_bibliographic_records.html[Merging Bibliographic
Records].





