The Bibliographic Record
~~~~~~~~~~~~~~~~~~~~~~~~
(((Cataloguing Policy)))
(((MARC 21 Format for Bibliographic Data)))
(((Normes MARC 21)))

The MARC 21 Format for Bibliographic Data is available in 
https://www.loc.gov/marc/bibliographic/[English] and in 
https://www.marc21.ca/M21/BIB/B001-Sommaire.html[French].  These websites contain the 
authoritative information on MARC fields and subfields.


Sitka's Minimum MARC Record
^^^^^^^^^^^^^^^^^^^^^^^^^^^
[[_sitka_minimum_marc_record]]
(((MARC Record)))
(((Leader)))
(((Control Fields)))
(((Fixed-Length Fields)))
(((Main Entry)))
(((Title)))
(((Publication Information)))
(((Physical Description)))
(((On Order Records)))
(((Brief Records)))
(((Standard Identifiers)))
(((ISBN)))
(((ISSN)))
(((UPC)))

MARC records for bibliographic titles in the Sitka catalogue should always meet the minimum 
requirements set in this policy and ideally should exceed them.

The following table outlines the fields that must ALWAYS be present in the MARC record.

|========
|MARC Field | Name | Required Subfields | Material Type | Description
|https://www.loc.gov/marc/bibliographic/bdleader.html[Leader] | Leader | N/A | ALL | Contains information required for Evergreen to process the record.
|https://www.loc.gov/marc/bibliographic/bd006.html[006] | Fixed-Length Data Elements - Additional Material Characteristics | N/A | Required for podcasts, e-books, e-audiobooks, e-videos, websites, streaming music, and 
streaming videos. | Contains coding used by Evergreen for search filters and format icons.  
|https://www.loc.gov/marc/bibliographic/bd007.html[007] | Physical Description Fixed Field | N/A | Required for 
soundrecordings (spoken and music), videorecordings, computer/video games, playaways, podcasts, 
e-books, e-audiobooks, e-videos, websites, streaming music, and streaming videos. | Contains coding 
used by Evergreen for search filters and format icons. 
|https://www.loc.gov/marc/bibliographic/bd008.html[008] | Fixed-Length Data Elements | N/A | ALL | Contains coding used by Evergreen for search filters and format icons. 
|https://www.loc.gov/marc/bibliographic/bd020.html[020]/https://www.loc.gov/marc/bibliographic/bd022.html[022]/https://www.loc.gov/marc/bibliographic/bd024.html[024] | Standard Identifiers | $a | ALL | Contains the standard identifier used internationally. Every bibliographic records should
have at least one 020, 022, or 024 field.
|https://www.loc.gov/marc/bibliographic/bd1xx.html[1XX] | Main Entry Fields | $a | ALL, 
with exceptions where the title is main entry. | Contains the entity responsible for the work (person, corporation, conference, etc.)
|https://www.loc.gov/marc/bibliographic/bd245.html[245] | Title Statement | $a, $c | ALL | Contains the title and author.
|https://www.loc.gov/marc/bibliographic/bd264.html[264] | Production, Publication, Distribution, Manufacture, and Copyright Notice | $a, $b, $c | 
ALL |  Contains the place of publication, publisher, and date of publication or copyright. This
is used instead of the 260 field in new records.
|https://www.loc.gov/marc/bibliographic/bd300.html[300] | Physical Description | $a, $c ($c not required for e-records) | ALL | Contains the physical description of the item 
including number of pages and dimensions.
|========

[NOTE]
======
Brief on order records are an exception as some of the required information may not yet be 
available. Brief on order records should always be updated to at least meet the minumum 
requirement when the item is received and added to the collection. For many records this 
is taken care of through routine xref:_consortial_batch_loading[batch loading] of full records.
======

A Good MARC Record
^^^^^^^^^^^^^^^^^^
(((MARC Record)))
(((Subject Headings)))
(((Edition)))
(((Content Type)))
(((Carrier Type)))
(((Media Type)))
(((Series)))
(((Note Fields)))
(((Added Entry)))
(((Electronic Location)))
(((856 Field)))



A good MARC record will contain more than just the bare minumum.  This makes it easier for patrons 
to locate the titles they're looking for in your public catalogue as well making it more evident 
what title is being described in the record so cataloguers can confidently attach their 
own holdings.

The fields included in a MARC record will vary depending on the type of material 
being described.

In addition to the mimumum required fields a good MARC record should also contain, where 
applicable, the following fields:

|========
|MARC Field | Name | Description
|https://www.loc.gov/marc/bibliographic/bd010.html[010]  | Library of Congress Control Number | Contains the unique number assigned by 
the Library of Congress.
|https://www.loc.gov/marc/bibliographic/bd016.html[016] | National Bibliographic Agency Control Number | Contains the unique number assigned by 
a national bibliographic agency, such as Library and Archives Canada.
|https://www.loc.gov/marc/bibliographic/bd250.html[250] | Edition Statement | Contains information about the version of the material, when 
multiple versions exist.
|https://www.loc.gov/marc/bibliographic/bd336.html[336] | Content Type | Found only in RDA records. Contains the content type of the title.
|https://www.loc.gov/marc/bibliographic/bd337.html[337] | Media Type | Found only in RDA records. Contains information on the type of device 
needed to view, play, run, etc. the title.
|https://www.loc.gov/marc/bibliographic/bd338.html[338] | Carrier Type | Found only in RDA records.  Contains information on the physical format
the title is stored on/in.
|https://www.loc.gov/marc/bibliographic/bd490.html[490] | Series Statement | Contains the series statement, including the series name. Older records
use the 440 field which is now obsolete.
|https://www.loc.gov/marc/bibliographic/bd5xx.html[5XX] | Note Fields | A variety of note fields are available which contain additional information
on the title. See xref:_library_specific_local_information[] for information on using local 
notes in Sitka's Evergreen.
|https://www.loc.gov/marc/bibliographic/bd6xx.html[6XX] | Subject Access Fields | A variety of subject fields are available which contain subject
terms to describe what the title is about. See xref:_local_subject_headings[] for information
on using local subject headings in Sitka's Evergreen.
|https://www.loc.gov/marc/bibliographic/bd70x75x.html[70X-75X] | Added Entry | Contains additional entities responsible for the work 
(person, corporation, conference, etc.) 
|https://www.loc.gov/marc/bibliographic/bd80x83x.html[80X-83X] | Series Added Entry | Contains additional information to aid in searching for series.
|https://www.loc.gov/marc/bibliographic/bd856.html[856] | Electronic Location and Access | Contains information for accessing an e-resource or 
resources related to a physical resource that are available electronically.  See 
xref:_library_specific_local_information[] for information on how to code this field in
Sitka's Evergreen.
|========

There are many more MARC fields that can be added to bibliographic records and cataloguers
with sufficient cataloguing knowledge should add them to records as applicable.

Local Information in Cataloguing
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(((Local Information)))

Library Specific Local Information
++++++++++++++++++++++++++++++++++
[[_library_specific_local_information]]

(((Note Fields)))
(((Subject Headings, Local)))
(((Local Subject Headings)))
(((856 Field)))

Some information included in bibliographic records is specific to a particular library.  In
the shared Sitka catalogue libraries are required to identify this information using a 
scoping subfield as outlined in the table below.

The information will apply to all items attached to the record belonging to 
the scoped library.

.Library Specific Local Information
[options="header"]
|=============
|MARC Field|Field Name|Scoping Subfield|OPAC Visible?|Use
|https://www.loc.gov/marc/bibliographic/bd506.html[506]|Restrictions on Access Note|5|Yes|Used to note who is allowed
 to access the resource.
|https://www.loc.gov/marc/bibliographic/bd521.html[521]|Target Audience Note|5|Yes|Used to indicate the 
audience the resource is intended for (e.g. reading level or video rating).
|https://www.loc.gov/marc/bibliographic/bd540.html[540]|Terms Governing Use and Reproduction Note|5|Yes|Used to note 
how the resource can be used (e.g. Public Performance Rights).
|https://www.loc.gov/marc/bibliographic/bd59x.html[590]|Local Notes|5|No|Used for any local notes that do not fit
 into another field.
|https://www.loc.gov/marc/bibliographic/bd59x.html[595]|Local Notes (Indexed)|5|No|Used for any local notes
 that need to be searchable in the public catalogue.
|https://www.loc.gov/marc/bibliographic/bd69x.html[690]|Local Subject Access Fields|5|Yes|Used for local subject
 headings (e.g. not Library of Congress or Canadian Subject Headings).
|https://www.loc.gov/marc/bibliographic/bd856.html[856]|Electronic Location and Access|9|Yes|Used 
to provide the URL for access to electronic resources.
|=============


[NOTE]
======
Libraries should only use the specified fields when entering local notes (590, 595) 
and local subject headings (690). These three fields are preserved when records are merged 
together.
======

Item Specific Local Information
+++++++++++++++++++++++++++++++
[[_item_specific_local_information]]

(((Statistical Category)))
(((Item Statistical Category)))
(((Item Note)))
(((Item Alert)))

Information that is specific to items should NEVER be included in the bibliographic record.
Instead this information should be included in the relevant item attribute so that it is
included in the item record.

The information will apply to the specific item.

.Item Specific Local Information
[options="header"]
|=============
|Name|Patron Visible|Use
|http://docs.libraries.coop/sitka/_item_alerts_notes_tags_and_statistical_categories.html#_item_statistical_category_values[Item
 Statistical Category]|No|Used for commonly repeated information about a specific item (e.g. vendor).
|http://docs.libraries.coop/sitka/_item_alerts_notes_tags_and_statistical_categories.html#_item_notes[Item Note]|No|Used 
for information specific to the item (e.g. Adopt a Book sponsor).
|http://docs.libraries.coop/sitka/_item_alerts_notes_tags_and_statistical_categories.html#_item_notes[Item Note] (Public)
|Yes|Used for information specific to the item that may be of interest to a patron (e.g. autographed copy).
|http://docs.libraries.coop/sitka/_item_alerts_notes_tags_and_statistical_categories.html#_item_alerts_2[Item Alert]|Yes|
Used for information that should been seen when an item is checked in or out (e.g. Damage or number of pieces to check for). CAUTION: some 3rd party self check machines cannot display item alerts.
|=============
