Adding Individual Bibliographic Records
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

All new bibliographic records added to the Sitka catalogue should be RDA records and 
follow the xref:_bibliographic_records[cataloguing standards].

Importing via Z39.50
^^^^^^^^^^^^^^^^^^^^

(((Bibliographic Records, Z39.50)))

When importing new records via Z39.50 cataloguers should edit the record as needed to ensure 
it accurately describes the title being catalogued.  

Local information from the record source should be removed as it does not apply to Sitka's 
Evergreen. This information is generally found in the 59X and 9XX fields of the MARC record.

[TIP]
=====
If a record for the exact item being catalogued is not available via Z39.50 but there is one
in the Sitka catalogue for the title in another format or edition, you can import 
a copy of the existing record and then edit it to match your new item.  

It is essential to make sure you edit the new record and not the existing record.
=====

Instructions on importing bibliographic records via Z39.50 can be found in Sitka's Evergreen Documentation 
in the section called
https://docs.libraries.coop/sitka/_adding_individual_records.html#_importing_bibliographic_records_via_z39_50_interface[Importing
Bibliographic Records via Z39.50].

Original Cataloguing
^^^^^^^^^^^^^^^^^^^^

(((Original Cataloguing)))

Original cataloguing will generally constitute a very small percentage of bibliographic records 
added to the Sitka database by a library.  Original cataloguing of bibliographic records 
should be done in Sitka's Evergreen only if there is no record available in the Sitka 
catalogue, via Z39.50, or from your vendor.

Bibliographic records created in Sitka's Evergreen MUST follow the 
xref:_cataloguing_standards[cataloguing standards] and meet Sitka's 
xref:_sitka_minimum_marc_record[Minimum MARC Record] requirements.

MARC templates for different formats are provided in Sitka's Evergreen to assist cataloguers.

Instructions for creating new bibliographic records can be found in Sitka's Evergreen Documentation in 
the section called
 https://docs.libraries.coop/sitka/_creating_new_records_for_bibliographic_resources.html[Creating 
 New Bibliographic Records].

For non-bibliographic records please refer to the  
xref:_non_bibliographic_records[policy on non-bibliographic records].

Using Placeholder Holdings
^^^^^^^^^^^^^^^^^^^^^^^^^^
(((On Order Records)))

Some libraries may add bibliographic records for titles before they have physically arrived
at the library so that patrons can place holds. Generally vendor record files will
include holdings information to automatically create these placeholder items.  For records
that already exist in the Sitka catalogue, brought in via Z39.50, or created as original
records cataloguers will need to manually create placeholder items.

These placeholder items are created as described in the 
http://docs.libraries.coop/sitka/add_holdings.html[Adding Holdings to Bibliographic Records] 
section of Sitka's Evergreen Documentation, but with temporary information used to 
fill some of the holdings fields.

Approved practice for cataloguers includes the following:

* Use fake barcodes which include your library code, and have somewhere to 
record where you are in the sequence. i.e. MPL1000, MPL1001, MPL1002
* Use ON ORDER as your call number.
* Use Evergreen's On order status for the item record.
* Have an On Order http://docs.libraries.coop/sitka/_holdings_templates.html[holdings
 template] for cataloguers to use.
* Create and use an ON ORDER 
http://docs.libraries.coop/sitka/_shelving_location_editor.html#_creating_a_shelving_location[shelving location],
 especially if your library uses a new 
book shelving location.

When the item arrives, the cataloguer simply updates the barcode, 
call number, and item attributes on the placeholder item rather than creating a new item.

[NOTE]
======
Bibliographic records that are more than 3 months old with no physical or electronic holdings 
attached are automatically deleted on a monthly basis so make sure you add placeholder holdings
within 3 months of adding the record.
======
