Batch Loading Bibliographic Records
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bibliographic records for physical and electronic resources can be batch loaded using 
files of MARC records from vendors.  Batch loading is done by Co-op Support 
and library cataloguing staff.

Libraries should ensure vendors are supplying them with RDA records and, when 
needed, advocate for records that follow cataloguing standards and include the 
xref:_sitka_minimum_marc_record[minimum
required information] for Sitka's Evergreen.

[NOTE]
======
The BC Libraries Cooperative reserves the right to limit the number of bibliographic
e-resource records to be loaded in batch into Sitka's Evergreen.  

Libraries should ensure the records that are being loaded are for resources relevant to their 
patrons and not simply because the record and resource is available.  Bibliographic records
take up space in the database and adding hundreds of thousands of records affects 
the services that can be offered and our hardware needs, which in turn affects the cost to 
use Sitka's Evergreen. 

If the total number of records for a new product will exceeed 50 000 records you MUST contact
https://bc.libraries.coop/support/[Co-op Support].
======

Consortial Batch Loading
^^^^^^^^^^^^^^^^^^^^^^^^

Co-op Support currently loads the following for Sitka libraries:

*Records for Physical Items*

* Enhanced on order and full records for ULS
* Enhanced on order and full records for Whitehots

For information about on order and full records from ULS and Whitehots please
refer to 
https://bc.libraries.coop/support/sitka/enhanced-on-order-records-and-shelf-ready-items/[Enhanced
On Order Records and Shelf Ready Items].

*Records for e-resources*

* BC Open Textbook for opted in Sitka libraries (free resource)
* Cantook Station for BC public libraries
* Overdrive for BC and Manitoba public libraries

To opt in to BC Open Textbooks please contact 
https://bc.libraries.coop/support/[Co-op Support].


Library Specific Batch Loading
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Co-op Support and library cataloguing staff batch load vendor files for products that
libraries subscribe to individually.

Acquisitions staff may batch load on order vendor records via the 
http://docs.libraries.coop/acquisitions/_load_marc_order_records.html[Load MARC Order Records]
interface.  Cataloguing staff may batch load vendor records via 
https://docs.libraries.coop/sitka/_batch_loading_bibliographic_records.html[MARC Batch Export/Import].



The following parameters should be used for the different types of records loaded in batch:


*On Order Records for Acquisitions*

* Record Match Set = SitkaMatch
* Merge Profile = Merge Using EXISTING Record
* Import Non-Matching Records = TRUE
* Merge On Best Match = TRUE

*Brief Records for Physical Items*

* Record Match Set = SitkaMatch
* Merge Profile = Merge Using EXISTING Record
* Import Non-Matching Records = TRUE
* Merge On Best Match = TRUE

*Full Records for Physical Items*

* Record Match Set = SitkaMatch
* Merge Profile = Merge Using INCOMING Record
* Import Non-Matching Records = TRUE

*Full Records for e-resources*

_For new records only. Please contact  https://bc.libraries.coop/support/[Co-op Support] 
if you will be loading update files._ 

* Record Match Set = NoMatch
* Merge Profile = Merge Using EXISTING Record (records are not actually merged as no 
matches will be found)
* Import Non-Matching Records = TRUE



If your library is subscribing to a new product that includes MARC records for e-resources 
please confirm with the vendor how their records are updated.  Some vendors supply update 
and deletion files while other vendors will send a full collection replacement file.  If 
you will require assistance from Co-op Support for loading, updating, or deleting please 
 https://bc.libraries.coop/support/[submit a ticket] and include who the vendor is and 
 all information they have provided you with about the MARC files they supply.


Please contact https://bc.libraries.coop/support/[Co-op Support] if you have questions
about batch loading.

E-resource Record Batch Deletion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Co-op Support can batch delete e-resource records when the vendor supplies a deletion file.
If deletion files are not available from the vendor, records for e-resources the vendor 
no longer offers will remain in the Sitka catalogue unless individually removed by 
library staff.  Instructions for removing e-resources individually can be 
found in Sitka’s Evergreen Documentation in the section called 
https://docs.libraries.coop/sitka/_deleting_holdings_for_electronic_resources.html[Deleting Holdings for Electronic Resources].

When investigating a new product please ask the vendor if they supply deletion files and 
if so ensure that they are included in your subscription.

Batch e-resource deletion is currently all done by Co-op Support.  Please contact
https://bc.libraries.coop/support/[Co-op Support] for assistance with e-resource
batch deletions.